const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://previews.dropbox.com/p/thumb/ABGyna7rFWu-hiqEzCd0qBDBXW6qxMnBF6YjtgPCUfOgS56lWAJKGxoQCOjxaDKe-EfdldMMqTEEihVdoUWPUT1vga6roTuHC2RSEh_vA1pctz2YMwICeRL6ieWSrMV8ejie5eG9qGxePTiGAZTi_2IgiRJ3G9jzXjTOw9jbSTbgOhRuRMpmpVRJX-1PNg5ELaaLfU2Gjqvm3HZlK9k7Ul6MxtPuO-5fHTrX_TR1AEYYRz4XFbD_ieFhm54HJUEI9yVaAYwGtakjpGTLVomOu3mAVHIaEN_AfegQ-0VggXj96lFi2bivZe4fEE1FuEK46NIQddKm2nW2MY2b0S0PNucfUWcyaLnCIOX4lcn9GiDQwA/p.jpeg?fv_content=true&size_mode=5',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://previews.dropbox.com/p/thumb/ABEvj9fi1KOZXz4CPIIhVoYn8lEWYD4GYw0ROWmvGlNB5QMkMv18jTBm4m2vfb9i940KPW2dQF8xq_zBmMGSPqvVAVpsDOxNKJqWzBTVuY1gpB9LUH6vAP_ywdBeD1nsWNAKl4XBoauv2yVprBOHUW8gbdKQK0TVyoDcklq8PPQcB5TBiEG9z3kpJ41pyn5rFviGXxZDIx8Pgq39TOFWFWoIgWPT2fHRW7CfhZ--D-j1NfRAN6xWTykSAGUkbY_pzWDvryrT_GBpt-DFsh9YOgDFO8Ou6DcgMorJfvq704uvCIzRdqmeVatU44-mCDvPu0_hQBeDC6AE5Vk0x7UWLAYmojRW2GzYw2Oxx1mbfx18rg/p.jpeg?fv_content=true&size_mode=5',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://previews.dropbox.com/p/thumb/ABGM8DvZLKgTsklRfQzntSFAGzVh0YFQvkLUNgJrrZUoWhxLOBooxKuSUzXFDuuenRIr_pDkEoOoUA44Z5DkF8RllacCcrYzp9MxAyA8sQNG8YKqv5LstPHl3-X-3AVqVDNby0Qbo3zP9xAXGCdGJj9Ox9B_VnN-j_Kw3a6pesvm9-dGqEZtsUX5eSAU_1QQ7aT9tmOuUTegNQReyinlx7LsH5ssRfUFiX-V5AxsTSLZGdYgP5xXJ7wb0bZnE_ZBMTiaw0CAYpj5WtxhOCuZV0Lw8HoxMWiRgXAgVJpH9jqNeWLytOEe-Bp3YA2y6vn1PyeCJLWSyQ2ya_Htz7uzS9FSdKpdGOkxoFmyf6re5xyn8w/p.jpeg?size=1280x960&size_mode=3',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://previews.dropbox.com/p/thumb/ABHAUi1INEvjri8tkICD24XSq3HWoyCuWGuI1XxI-QR10Genle6F4pjHEaW8Zm0mK1-JpC3UACDGqb0ung2QEDaKSnYB30r7wT6za9UM1BHNWrmVR_Z573Wii-lYs5JxlNA_0hLFYeI9vPJQsUU5ibLCzTwGbkwdpkixILH7NVeP4cT1k8pIqzkO5JMvAXp30FOh_HSDiElzphLMuTQ2mrM-hbyfd2ohXU3zX_KucZhukL6c_yNrdmOU4N4Za8SahK5gRbcxPKd_BuKzj0Oaz9pZa3qPG9y7Z7NqsWuMPrgPZWjMySj29zo9A5SeUBwaNM5Dyq5T1LJgLvq3IxWeHZX2v5WrXDFeH5XOmS1eWxJmbA/p.jpeg?fv_content=true&size_mode=5',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://previews.dropbox.com/p/thumb/ABGhCOfJPoBGN6fBey7oGFx6xA13cpn04bw9tfChSTR-TV0ptRa723wp1k-z_q5zXU5pNqg2ec0-02XlsX7869Hn9RKDEf3Z2v-KNDCa87T5fG0ZxpYg9Du6kWKEzLO0Xd7T5AMFG3vNE9jYczLph3xR6y3KAjgH7y1u6NjDG7ab4CWtfAVGp2oB-eHZxhRDubDnzuKOkIialCVCr5b-S30jPyddyZE6v4TgiQqupV57ovk4439WA12uO-hjzDYKQcB6YBYtOWNKEaLHmhxXSp08STgF0ZRxlVAWID6wGpG0HbtGxyxp19xAbIQM1i_sVhPcrVGhdQ37wY-87GucN3CBwskdjmls0UgI-m0PwWkwFw/p.jpeg?fv_content=true&size_mode=5',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://previews.dropbox.com/p/thumb/ABGbw16RuxMdjpWme6FRtcJrEiqb6W__Bnko-t9CxSEb0OrOvd3HCWOLZ0_TOpk31hXaA8b18vFACcIePEHNrHtqmFuQxjyuELMOwz1QhkPQnUUwOF61oc8yssR-J7P1c51vlE5fYm78X2OvRJKcfIXeACRK0e07oNiiGL9oy-1sK9ohxE2denhW962zoSGXosUWdt8ZUZ54EKSbM6tX04NjSzBSbk0hin0owS_3mRhJp9KkSXo7i893pI4Gmj6XVrdnJSmK0WQGraitodkBYus4_LtPhdDZ_nomkIg6ZwaRSXsr2X1OYNpZ82Up49gWLE5CnikEMhY_CAbvbmQtIGU4iQ-HEGbprYlz4w4DNRfwGA/p.jpeg?fv_content=true&size_mode=5',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://previews.dropbox.com/p/thumb/ABHhfjkUZFbWibRYjaQH30_kGjj78CBeY5jpOPEzQUfEEhfnOjmCz43Zm315RxfSk9BLqzSB_cA0FKJ7JJ4Pkg5wAEf5SXTXyn7OYI156v1D8z_-hoAwKs-07agBNT5T30cHERY9XWModgrEnmj9zeF07IQ0T5tGDBasUehLTPMYMPwOrhCHPHlu1Tt6EPktzIq-pmSVvAsBmPjJR9D8rJQyHTzdusld0RCqE5Wh2MMPCctLQSR4rEC6qVg1QDQAKGnwXY4t2FupCOSDvtJcDVGsPGR2I0oabyzTgL8CH3KF819KNDwiw7-b7BmC4pB7zUp-TTQIr9bvcrevk7ZjOgJnWg8hXnSWD1B318O9d2GGpw/p.jpeg?fv_content=true&size_mode=5',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://previews.dropbox.com/p/thumb/ABFeaP8Y9uQhbuZrRHfNk1KWmwG-J2Oh2hco9ZOOjBYFeAC8KXtUni36Y2NyJ_n7wnP22s6UNgLjCiPSJifc2ew5SyjvqDqVhzuNIRLQHcTz9RMM1X9lJNYadqTIhncYZQOY3bJ18WD45nPz0ts1liE6JND2IaoKfCZNZw8LHsmxQ4LD9Ywl_AKNJfDLgw7dQ7y1D02iEghzVXULMCO-Ly718FcjD6Hx6UkkpXCyD276T6lPCVYv7mxWklC5jSKJGNjgST9H43rd4X-PhhNqGklYaWrwxaxeA5d7ENWn0YXnyDsU0jos3gw5MPP3KiSj5LAcImxesvdUJLsmMmify457i9iVmVt3glJz5bX8adjcag/p.jpeg?fv_content=true&size_mode=5',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://previews.dropbox.com/p/thumb/ABFhwUYI9chnBaPTyk28lLRvqKb9VCE3JBuZasrGCC2vF54fRMxAsBWIMuurN_E9ghfffsIdhDhP0S7nt-sJrCN2XmUBp487BnfNDHuKGaFAxLdPh8ITGS-K2yPtrbB2p_QawYzZ1fmJ9yOKa2MLun-zmnpojDB_2QqZTg1BToXhO9q0XRVNsEJmZOaypt-v-2ATooeHtZ_-UIkuY3p7xEdUiUpdecpL8t7_ZjwML8HEYzjjUhTzq1vL6CMYv1w70qpQ4d42I_vZaAY4VZX4yigCIsbaJhB-VBYWbq-gDX36UZJg07r4eXyRrmR17BCSIjU_RCHGosU0v3RcicVVQjUm7n5hh6iMXMYwVUEQoDIqVw/p.jpeg?fv_content=true&size_mode=5',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
